# Generated by Django 2.0.7 on 2018-07-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinosaur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.CharField(blank=True, default='', max_length=100)),
                ('tribe', models.CharField(blank=True, default='', max_length=100)),
                ('acquired', models.BooleanField(choices=[(True, 'Tamed'), (False, 'Breeded')])),
                ('effectiveness', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.BooleanField(choices=[(True, 'Alive'), (False, 'Dead')])),
                ('sexe', models.BooleanField(choices=[(True, 'Male'), (False, 'Female')])),
                ('health', models.IntegerField(default=0)),
                ('stamina', models.IntegerField(default=0)),
                ('oxygen', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('weight', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('race',),
            },
        ),
    ]
